language: c
compiler:
    - gcc
    - clang
before_script:
    - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
    - git clone git@github.com:antirez/redis.git redis && cd redis
script: ./configure --add-module=../ && make
notifications:
    recipients:
        - lwch748@gmail.com
    email:
        on_success: change
        on_failure: always
