language: c
compiler:
    - gcc
    - clang
before_script: git submodule update --init --recursive && cd nginx
script: ./configure --add-module=../ && make
notifications:
    recipients:
        - lwch748@gmail.com
    email:
        on_success: change
        on_failure: always
