language: c
compiler:
    - gcc
    - clang
before_script:
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - git clone --depth=50 --branch=unstable git@github.com:antirez/redis.git redis && cd redis
script: ./configure --add-module=../ && make
notifications:
    recipients:
        - lwch748@gmail.com
    email:
        on_success: change
        on_failure: always
